deployment:
  tasks:
    - export DEPLOYPATH=/home2/laccademiadellam/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp grazie-ebook.html $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/ebook/files/