---
deployment:
  tasks:
    - export DEPLOYPATH=/home/laccademiadellam/public_html/
    - /bin/mkdir -p $DEPLOYPATH

    # HTML
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/cp grazie-ebook.html $DEPLOYPATH/

    # cartella ebook con pdf
    - /bin/cp -R ebook $DEPLOYPATH/

    # assets
    - /bin/cp -R images $DEPLOYPATH/
    - /bin/cp -R css $DEPLOYPATH/
    - /bin/cp -R js $DEPLOYPATH/